on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: build pages
        run: npm run build
      
      - name: Deploy to github pages
        run: npm run deploy
