on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: npm install
        run: npm install
      - name: build pages
        run: npm run build

      - name: Setup git account
        run: |
          git config --global user.email "<>>"
          git config --global user.name "github_bot"
      - name: Deploy to github pages
        run: npm run deploy
